//
//  AppDatabase.swift
//  BrickPhone
//
//  Created by Marcelo Monsalve on 12/12/24.
//


import Foundation

enum AppDatabase {
    static let knownApps: [String: String] = [
        "1Password": "onepassword://",
        "Adobe Acrobat": "acrobat://",
        "Adobe Creative Cloud": "creativecloud://",
        "Adobe Lightroom": "lightroom://",
        "Adobe Photoshop Express": "psx://",
        "Adobe Scan": "scan://",
        "Airbnb": "airbnb://",
        "Amazon": "amazon://",
        "Amazon Music": "music://",
        "Ancestry": "ancestry://",
        "Anchor": "anchorfm://",
        "Apple Music": "music://",
        "Apple Music Classical": "classical://",
        "Apple News": "applenews://",
        "Apple Store": "itms-apps://itunes.apple.com",
        "Apple TV": "videos://",
        "Asana": "asana://",
        "Audible": "audible://",
        "Bank of America": "bofa://",
        "BBC News": "bbcnews://",
        "Bear Notes": "bear://",
        "Binance": "binance://",
        "Bloomberg": "bloomberg://",
        "Box": "box://",
        "Brave Browser": "brave://",
        "Calculator": "calculator://",
        "Calendar": "calshow://",
        "Camera": "camera://",
        "Canary Mail": "canary://",
        "Canva": "canva://",
        "Cash App": "squarecash://",
        "Castro": "castro2://",
        "Chase Mobile": "chase://",
        "CityMapper": "citymapper://",
        "Clips": "clips://",
        "Coinbase": "coinbase://",
        "Contacts": "contacts://",
        "DayOne": "dayone://",
        "Deliveroo": "deliveroo://",
        "Delta Air Lines": "delta://",
        "Discord": "discord://",
        "Disney+": "disneyplus://",
        "DoorDash": "doordash://",
        "Dropbox": "dbapi-1://",
        "DuckDuckGo": "ddgLaunch://",
        "Duolingo": "duolingo://",
        "eBay": "ebay://",
        "Edge Browser": "microsoft-edge://",
        "Evernote": "evernote://",
        "Facebook": "fb://",
        "Facebook Messenger": "fb-messenger://",
        "FaceTime": "facetime://",
        "FaceTime Audio": "facetime-audio://",
        "Fantastical": "fantastical2://",
        "Files": "shareddocuments://",
        "Find My": "findmy://",
        "Firefox": "firefox://",
        "Fitbit": "fitbit://",
        "Flickr": "flickr://",
        "Forest": "forest://",
        "Gboard": "gboard://",
        "GitHub": "github://",
        "Gmail": "googlegmail://",
        "Goodreads": "goodreads://",
        "Google": "google://",
        "Google Assistant": "googleassistant://",
        "Google Calendar": "googlecalendar://",
        "Google Chat": "googlechat://",
        "Google Chrome": "googlechrome://",
        "Google Classroom": "googleclassroom://",
        "Google Docs": "googledocs://",
        "Google Drive": "googledrive://",
        "Google Earth": "googleearth://",
        "Google Keep": "comgooglekeep://",
        "Google Maps": "googlemaps://",
        "Google Meet": "googlemeet://",
        "Google Photos": "googlephotos://",
        "Google Sheets": "googlesheets://",
        "Google Slides": "googleslides://",
        "Google Translate": "googletranslate://",
        "GoPro": "gopro://",
        "HBO GO": "hbogo://",
        "HBO Max": "hbomax://",
        "Health": "x-apple-health://",
        "Home": "home://",
        "Home Depot": "homedepot://",
        "Hulu": "hulu://",
        "iBooks": "ibooks://",
        "IFTTT": "ifttt://",
        "IMDb": "imdb://",
        "iMovie": "imovie://",
        "Indeed Jobs": "indeed://",
        "Instagram": "instagram://",
        "Instacart": "instacart://",
        "Instapaper": "instapaper://",
        "Kahoot": "kahoot://",
        "Kayak": "kayak://",
        "Khan Academy": "khanacademy://",
        "LastPass": "lastpass://",
        "Line": "line://",
        "LinkedIn": "linkedin://",
        "Lyft": "lyft://",
        "Mail": "message://",
        "Maps": "maps://",
        "Marco Polo": "marcopolo://",
        "McDonalds": "mcdonalds://",
        "Medium": "medium://",
        "Messages": "sms://",
        "Microsoft Excel": "ms-excel://",
        "Microsoft OneDrive": "onedrive://",
        "Microsoft OneNote": "onenote://",
        "Microsoft Outlook": "ms-outlook://",
        "Microsoft PowerPoint": "ms-powerpoint://",
        "Microsoft Teams": "msteams://",
        "Microsoft To Do": "mstodo://",
        "Microsoft Word": "ms-word://",
        "Mint": "mint://",
        "MyFitnessPal": "myfitnesspal://",
        "Netflix": "nflx://",
        "Nike Run Club": "nikerunclub://",
        "Nintendo Switch Online": "nso://",
        "Notes": "mobilenotes://",
        "Notion": "notion://",
        "Omnifocus": "omnifocus://",
        "Opera Browser": "opera://",
        "Overcast": "overcast://",
        "Pandora": "pandora://",
        "ParcelApp": "parcel://",
        "PayPal": "paypal://",
        "Peak - Brain Training": "peak://",
        "Phone": "tel://",
        "Photos": "photos-redirect://",
        "Pinterest": "pinterest://",
        "Plex": "plex://",
        "Podcasts": "podcasts://",
        "Pokemon GO": "pokemongo://",
        "Postmates": "postmates://",
        "ProtonMail": "protonmail://",
        "ProtonVPN": "protonvpn://",
        "Quizlet": "quizlet://",
        "Reddit": "reddit://",
        "Reminders": "x-apple-reminder://",
        "Ring": "ring://",
        "Robinhood": "robinhood://",
        "Safari": "x-web-search://",
        "Shazam": "shazam://",
        "Settings": "app-prefs://",
        "Shopify": "shopify://",
        "Shortcuts": "shortcuts://",
        "Signal": "sgnl://",
        "Skype": "skype://",
        "Slack": "slack://",
        "Snapchat": "snapchat://",
        "SoundCloud": "soundcloud://",
        "Spark Mail": "readdle-spark://",
        "Spotify": "spotify://",
        "Square Point of Sale": "square://",
        "Starbucks": "sbuxcard://",
        "Strava": "strava://",
        "Telegram": "tg://",
        "Tesla": "tesla://",
        "Things": "things://",
        "TikTok": "tiktok://",
        "Todoist": "todoist://",
        "Trading 212": "trading212://",
        "Trello": "trello://",
        "Tripadvisor": "tripadvisor://",
        "Truecaller": "truecaller://",
        "Tumblr": "tumblr://",
        "Twitch": "twitch://",
        "Twitter": "twitter://",
        "Uber": "uber://",
        "Uber Eats": "ubereats://",
        "United Airlines": "united://",
        "UPS": "ups://",
        "Venmo": "venmo://",
        "Vimeo": "vimeo://",
        "VLC": "vlc://",
        "Voice Memos": "voicememos://",
        "VSCO": "vsco://",
        "Wallet": "shoebox://",
        "Walmart": "walmart://",
        "Watch": "itms-watch://",
        "Waze": "waze://",
        "WeChat": "weixin://",
        "WhatsApp": "whatsapp://",
        "WhatsApp Business": "whatsappbusiness://",
        "Yelp": "yelp://",
        "YouTube": "youtube://",
        "YouTube Music": "youtubemusic://",
        "YouTube TV": "youtubetv://",
        "Zoom": "zoom://"
    ]
    
    static func generateShortcutScheme(for appName: String) -> String {
        "shortcuts://run-shortcut?name=\(appName)"
    }
    
    static func getAppURL(_ appName: String) -> String? {
        knownApps[appName]
    }
    
    static func searchApps(matching query: String) -> [String: String] {
        knownApps.filter { (key, _) in
            key.lowercased().contains(query.lowercased())
        }
    }
}
